language: python
sudo: required
python:
    - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsnappy-dev
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-doctest --with-coverage
after_success:
  - coveralls

